// <copyright file="ItemDropByRankConfiguration.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.GameLogic.PlugIns;

using MUnique.OpenMU.DataModel.Composition;

/// <summary>
/// Configuration for the <see cref="ItemDropByRankPlugIn"/>.
/// Every item has a rank, and the rank defines the monster level window and the chance.
/// Inside the window, the item drops from its start level up to the end of the window:
/// gloves from the start, then boots, helm, pants, armor; weapons and shields like pants.
/// </summary>
public class ItemDropByRankConfiguration
{
    /// <summary>
    /// Gets or sets a value indicating whether items also drop in mini games.
    /// </summary>
    [Display(Name = "Apply in mini games", Description = "If enabled, items also drop from monsters in mini games (Blood Castle, Devil Square, Chaos Castle, ...). Mini games have their own rewards, so this is off by default.")]
    public bool ApplyInMiniGames { get; set; }

    /// <summary>
    /// Gets or sets the luck chance in percent.
    /// </summary>
    [Display(Name = "Luck chance (%)", Description = "Chance that a dropped item has the luck option, if the item can have it.")]
    public float LuckChancePercent { get; set; } = 20f;

    /// <summary>
    /// Gets or sets the skill chance in percent.
    /// </summary>
    [Display(Name = "Skill chance (%)", Description = "Chance that a dropped weapon has its skill, if the item can have it.")]
    public float SkillChancePercent { get; set; } = 30f;

    /// <summary>
    /// Gets or sets the ranks.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Ranks", Description = "Monster level window and chance per rank. Chance of one specific item per kill = 1 / 'One in kills'.")]
    public ICollection<ItemDropRank> Ranks { get; set; } = CreateDefaultRanks();

    /// <summary>
    /// Gets or sets the items.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Items", Description = "Items which drop by rank. At most one item drops per kill. Generated by tools/balance/item_drop_sql.py.")]
    public ICollection<ItemDropByRankEntry> Items { get; set; } = new List<ItemDropByRankEntry>();

    private static ICollection<ItemDropRank> CreateDefaultRanks() => new List<ItemDropRank>
    {
        new() { Rank = 1, MinimumMonsterLevel = 1, MaximumMonsterLevel = 52, OneInKills = 13_500 },
        new() { Rank = 2, MinimumMonsterLevel = 50, MaximumMonsterLevel = 90, OneInKills = 28_200 },
        new() { Rank = 3, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130, OneInKills = 50_000 },
        new() { Rank = 4, MinimumMonsterLevel = 130, MaximumMonsterLevel = 170, OneInKills = 77_600 },
        new() { Rank = 5, MinimumMonsterLevel = 170, MaximumMonsterLevel = 220, OneInKills = 117_000 },
        new() { Rank = 6, MinimumMonsterLevel = 220, MaximumMonsterLevel = 270, OneInKills = 121_900 },
        new() { Rank = 7, MinimumMonsterLevel = 270, MaximumMonsterLevel = 320, OneInKills = 180_000 },
        new() { Rank = 8, MinimumMonsterLevel = 320, MaximumMonsterLevel = 400, OneInKills = 240_400 },
    };

    /// <summary>
    /// A rank.
    /// </summary>
    public class ItemDropRank
    {
        /// <summary>
        /// Gets or sets the rank number.
        /// </summary>
        [Display(Name = "Rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Gets or sets the minimum monster level of the window.
        /// </summary>
        [Display(Name = "Minimum monster level")]
        public int MinimumMonsterLevel { get; set; }

        /// <summary>
        /// Gets or sets the maximum monster level of the window.
        /// </summary>
        [Display(Name = "Maximum monster level")]
        public int MaximumMonsterLevel { get; set; }

        /// <summary>
        /// Gets or sets the chance of one specific item as "one in N kills".
        /// </summary>
        [Display(Name = "One in kills", Description = "Chance of one specific item of this rank per kill: 1 / N. 0 disables the rank.")]
        public int OneInKills { get; set; }
    }

    /// <summary>
    /// An item which drops by rank.
    /// </summary>
    public class ItemDropByRankEntry
    {
        /// <summary>
        /// Gets or sets the name, only for the overview.
        /// </summary>
        [Display(Name = "Name", Description = "Only for the overview; the item is identified by group and number.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the item group.
        /// </summary>
        [Display(Name = "Item group")]
        public short ItemGroup { get; set; }

        /// <summary>
        /// Gets or sets the item number.
        /// </summary>
        [Display(Name = "Item number")]
        public short ItemNumber { get; set; }

        /// <summary>
        /// Gets or sets the rank.
        /// </summary>
        [Display(Name = "Rank")]
        public int Rank { get; set; }

        /// <summary>
        /// Gets or sets the minimum monster level. 0 = by the item kind inside the rank window.
        /// </summary>
        [Display(Name = "Minimum monster level", Description = "0 = automatic: gloves from the start of the rank window, then boots, helm, pants, armor (each 1/6 of the window later); weapons and shields like pants.")]
        public int MinimumMonsterLevel { get; set; }

        /// <summary>
        /// Gets or sets the chance override as "one in N kills". 0 = the chance of the rank.
        /// </summary>
        [Display(Name = "One in kills", Description = "0 = the chance of the rank. Used e.g. for the intermediate sets of rank 5 and 7.")]
        public int OneInKills { get; set; }
    }
}
