// <copyright file="QuestItemDropMultiplierPlugIn.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.GameLogic.PlugIns;

using System.Runtime.InteropServices;
using MUnique.OpenMU.DataModel.Composition;
using MUnique.OpenMU.PlugIns;

/// <summary>
/// Multiplies the drop chance of quest items (e.g. Scroll of Emperor, Ring of Honor of the class change quests)
/// for specific monsters, e.g. bosses which take much longer to kill.
/// </summary>
[PlugIn]
[Display(Name = "Quest item drop multipliers", Description = "Multiplies the drop chance of quest items for specific monsters (bosses). Generated by tools/balance/boss_drop_sql.py.")]
[Guid("A6C3E8F1-2B4D-4E79-9C15-3F8B7D2E6A40")]
public class QuestItemDropMultiplierPlugIn : IFeaturePlugIn, ISupportCustomConfiguration<QuestItemDropMultiplierConfiguration>, ISupportDefaultCustomConfiguration
{
    /// <inheritdoc />
    public QuestItemDropMultiplierConfiguration? Configuration { get; set; }

    /// <inheritdoc />
    public object CreateDefaultConfig() => new QuestItemDropMultiplierConfiguration();

    /// <summary>
    /// Gets the multiplier of the quest item chances for a monster.
    /// </summary>
    /// <param name="monsterNumber">The monster number.</param>
    /// <returns>The multiplier; 1 for monsters which are not listed.</returns>
    public float GetMultiplier(short monsterNumber) => MonsterDropMultiplier.Get(this.Configuration?.MonsterMultipliers, monsterNumber);
}

/// <summary>
/// The configuration of the <see cref="QuestItemDropMultiplierPlugIn"/>.
/// </summary>
public class QuestItemDropMultiplierConfiguration
{
    /// <summary>
    /// Gets or sets the multipliers for specific monsters.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Monster multipliers", Description = "Multiplies the chances of quest items for specific monsters (bosses). Monsters which are not listed use 1.")]
    public ICollection<MonsterDropMultiplier> MonsterMultipliers { get; set; } = new List<MonsterDropMultiplier>();
}
