// <copyright file="SkillBookDropConfiguration.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.GameLogic.PlugIns;

using MUnique.OpenMU.DataModel.Composition;

/// <summary>
/// The configuration of the <see cref="SkillBookDropPlugIn"/>.
/// </summary>
public class SkillBookDropConfiguration
{
    /// <summary>
    /// Gets or sets a value indicating whether skill books drop in mini games.
    /// </summary>
    [Display(Name = "Apply in mini games", Description = "If enabled, skill books also drop from monsters in mini games.")]
    public bool ApplyInMiniGames { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether the chance grows with the monster level inside the window of a book.
    /// </summary>
    [Display(Name = "Chance grows inside the window", Description = "If enabled, the chance of a book grows linearly from x0.5 at the first monster level of its window to x1.5 at the last one (x1 on average).")]
    public bool GrowingChance { get; set; } = true;

    /// <summary>
    /// Gets or sets the skill books which can drop.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Skill books", Description = "Every book is rolled independently on each kill of a monster within its level range. Generated by tools/balance/skill_books.py.")]
    public ICollection<SkillBookDropEntry> Books { get; set; } = CreateDefaultBooks();

    /// <summary>
    /// Gets or sets the multipliers for specific monsters, e.g. bosses which take much longer to kill.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Monster multipliers", Description = "Multiplies the chances for specific monsters (bosses). Monsters which are not listed use 1. Use 0 to disable the drop of a monster.")]
    public ICollection<MonsterDropMultiplier> MonsterMultipliers { get; set; } = new List<MonsterDropMultiplier>();

    private static ICollection<SkillBookDropEntry> CreateDefaultBooks() => new List<SkillBookDropEntry>
    {
        // generated:start
        new() { Name = "Orb of Summoning", ItemGroup = 12, ItemNumber = 11, ChancePercent = 0.025f, MinimumMonsterLevel = 1, MaximumMonsterLevel = 41 },
        new() { Name = "Scroll of Fire Ball", ItemGroup = 15, ItemNumber = 3, ChancePercent = 0.022956f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 45 },
        new() { Name = "Orb of Healing", ItemGroup = 12, ItemNumber = 8, ChancePercent = 0.0202f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 45 },
        new() { Name = "Scroll of Power Wave", ItemGroup = 15, ItemNumber = 10, ChancePercent = 0.019357f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 45 },
        new() { Name = "Orb of Greater Defense", ItemGroup = 12, ItemNumber = 9, ChancePercent = 0.016321f, MinimumMonsterLevel = 10, MaximumMonsterLevel = 50 },
        new() { Name = "Scroll of Lighting", ItemGroup = 15, ItemNumber = 2, ChancePercent = 0.016321f, MinimumMonsterLevel = 10, MaximumMonsterLevel = 50 },
        new() { Name = "Scroll of Teleport", ItemGroup = 15, ItemNumber = 5, ChancePercent = 0.013762f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 55 },
        new() { Name = "Orb of Greater Damage", ItemGroup = 12, ItemNumber = 10, ChancePercent = 0.013187f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 55 },
        new() { Name = "Orb of Impale", ItemGroup = 12, ItemNumber = 13, ChancePercent = 0.012109f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 55 },
        new() { Name = "Scroll of Meteorite", ItemGroup = 15, ItemNumber = 1, ChancePercent = 0.011604f, MinimumMonsterLevel = 20, MaximumMonsterLevel = 60 },
        new() { Name = "Scroll of Ice", ItemGroup = 15, ItemNumber = 6, ChancePercent = 0.009784f, MinimumMonsterLevel = 20, MaximumMonsterLevel = 60 },
        new() { Name = "Scroll of Poison", ItemGroup = 15, ItemNumber = 0, ChancePercent = 0.007906f, MinimumMonsterLevel = 25, MaximumMonsterLevel = 65 },
        new() { Name = "Scroll of Flame", ItemGroup = 15, ItemNumber = 4, ChancePercent = 0.006388f, MinimumMonsterLevel = 30, MaximumMonsterLevel = 70 },
        new() { Name = "Drain Life Parchment", ItemGroup = 15, ItemNumber = 20, ChancePercent = 0.006388f, MinimumMonsterLevel = 30, MaximumMonsterLevel = 70 },
        new() { Name = "Scroll of Twister", ItemGroup = 15, ItemNumber = 7, ChancePercent = 0.005161f, MinimumMonsterLevel = 35, MaximumMonsterLevel = 75 },
        new() { Name = "Sleep Parchment", ItemGroup = 15, ItemNumber = 24, ChancePercent = 0.005161f, MinimumMonsterLevel = 35, MaximumMonsterLevel = 75 },
        new() { Name = "Orb of Twisting Slash", ItemGroup = 12, ItemNumber = 7, ChancePercent = 0.003829f, MinimumMonsterLevel = 40, MaximumMonsterLevel = 80 },
        new() { Name = "Scroll of Evil Spirit", ItemGroup = 15, ItemNumber = 8, ChancePercent = 0.00337f, MinimumMonsterLevel = 45, MaximumMonsterLevel = 85 },
        new() { Name = "Orb of Greater Fortitude", ItemGroup = 12, ItemNumber = 14, ChancePercent = 0.0022f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 95 },
        new() { Name = "Orb of Fire Slash", ItemGroup = 12, ItemNumber = 16, ChancePercent = 0.0022f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 95 },
        new() { Name = "Scroll of Hellfire", ItemGroup = 15, ItemNumber = 9, ChancePercent = 0.0022f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 95 },
        new() { Name = "Orb of Penetration", ItemGroup = 12, ItemNumber = 17, ChancePercent = 0.001855f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 95 },
        new() { Name = "Increase Block Parchment", ItemGroup = 15, ItemNumber = 36, ChancePercent = 0.001436f, MinimumMonsterLevel = 60, MaximumMonsterLevel = 100 },
        new() { Name = "Orb of Death Stab", ItemGroup = 12, ItemNumber = 19, ChancePercent = 0.001319f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 105 },
        new() { Name = "Scroll of FireBurst", ItemGroup = 12, ItemNumber = 21, ChancePercent = 0.001211f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 105 },
        new() { Name = "Scroll of Aqua Beam", ItemGroup = 15, ItemNumber = 11, ChancePercent = 0.001211f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 105 },
        new() { Name = "Chain Lightning Parchment", ItemGroup = 15, ItemNumber = 19, ChancePercent = 0.00116f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 105 },
        new() { Name = "Scroll of Soul Barrier", ItemGroup = 15, ItemNumber = 15, ChancePercent = 0.001066f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Rageful Blow", ItemGroup = 12, ItemNumber = 12, ChancePercent = 0.001021f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Cometfall", ItemGroup = 15, ItemNumber = 12, ChancePercent = 0.000938f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Damage Reflection Parchment", ItemGroup = 15, ItemNumber = 22, ChancePercent = 0.000938f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Chain Drive Parchment", ItemGroup = 15, ItemNumber = 30, ChancePercent = 0.000938f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Ice Arrow", ItemGroup = 12, ItemNumber = 18, ChancePercent = 0.000898f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Critical Damage", ItemGroup = 12, ItemNumber = 23, ChancePercent = 0.000861f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Teleport Ally", ItemGroup = 15, ItemNumber = 14, ChancePercent = 0.000825f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Berserker Parchment", ItemGroup = 15, ItemNumber = 23, ChancePercent = 0.000825f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Inferno", ItemGroup = 15, ItemNumber = 13, ChancePercent = 0.000667f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Dragon Roar Parchment", ItemGroup = 15, ItemNumber = 32, ChancePercent = 0.000612f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Increase Health Parchment", ItemGroup = 15, ItemNumber = 35, ChancePercent = 0.000612f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Electric Spark", ItemGroup = 12, ItemNumber = 24, ChancePercent = 0.000562f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Ice Storm", ItemGroup = 15, ItemNumber = 17, ChancePercent = 0.000539f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Lightning Shock Parchment", ItemGroup = 15, ItemNumber = 21, ChancePercent = 0.000539f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Weakness Parchment", ItemGroup = 15, ItemNumber = 26, ChancePercent = 0.000539f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Decay", ItemGroup = 15, ItemNumber = 16, ChancePercent = 0.000474f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Summon", ItemGroup = 12, ItemNumber = 22, ChancePercent = 0.000435f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Destruction", ItemGroup = 12, ItemNumber = 44, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Multi-Shot", ItemGroup = 12, ItemNumber = 45, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Recovery", ItemGroup = 12, ItemNumber = 46, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Flame Strike", ItemGroup = 12, ItemNumber = 47, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Chaotic Diseier", ItemGroup = 12, ItemNumber = 48, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Nova", ItemGroup = 15, ItemNumber = 18, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Wizardry Enhance", ItemGroup = 15, ItemNumber = 28, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Gigantic Storm", ItemGroup = 15, ItemNumber = 29, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Dark Side Parchment", ItemGroup = 15, ItemNumber = 31, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Dragon Slasher Parchment", ItemGroup = 15, ItemNumber = 33, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Ignore Defense Parchment", ItemGroup = 15, ItemNumber = 34, ChancePercent = 0.0004f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Fire Scream", ItemGroup = 12, ItemNumber = 35, ChancePercent = 0.000367f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Innovation Parchment", ItemGroup = 15, ItemNumber = 27, ChancePercent = 0.00025f, MinimumMonsterLevel = 100, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Summoning +1", ItemGroup = 12, ItemNumber = 11, ItemLevel = 1, ChancePercent = 0.014987f, MinimumMonsterLevel = 10, MaximumMonsterLevel = 50 },
        new() { Name = "Orb of Summoning +2", ItemGroup = 12, ItemNumber = 11, ItemLevel = 2, ChancePercent = 0.008985f, MinimumMonsterLevel = 25, MaximumMonsterLevel = 65 },
        new() { Name = "Orb of Summoning +3", ItemGroup = 12, ItemNumber = 11, ItemLevel = 3, ChancePercent = 0.005386f, MinimumMonsterLevel = 35, MaximumMonsterLevel = 75 },
        new() { Name = "Orb of Summoning +4", ItemGroup = 12, ItemNumber = 11, ItemLevel = 4, ChancePercent = 0.003229f, MinimumMonsterLevel = 45, MaximumMonsterLevel = 85 },
        new() { Name = "Orb of Summoning +5", ItemGroup = 12, ItemNumber = 11, ItemLevel = 5, ChancePercent = 0.001936f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 95 },
        new() { Name = "Orb of Summoning +6", ItemGroup = 12, ItemNumber = 11, ItemLevel = 6, ChancePercent = 0.00116f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 105 },
        // generated:end
    };

    /// <summary>
    /// A skill book which can drop.
    /// </summary>
    public class SkillBookDropEntry
    {
        /// <summary>
        /// Gets or sets the name, only for the overview.
        /// </summary>
        [Display(Name = "Name", Description = "Only for the overview; the item is identified by group and number.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the item group.
        /// </summary>
        [Display(Name = "Item group")]
        public short ItemGroup { get; set; }

        /// <summary>
        /// Gets or sets the item number.
        /// </summary>
        [Display(Name = "Item number")]
        public short ItemNumber { get; set; }

        /// <summary>
        /// Gets or sets the item level (Orb of Summoning +1 ... +6 teaches the stronger summons).
        /// </summary>
        [Display(Name = "Item level")]
        public byte ItemLevel { get; set; }

        /// <summary>
        /// Gets or sets the chance per kill in percent.
        /// </summary>
        [Display(Name = "Chance per kill (%)")]
        public float ChancePercent { get; set; }

        /// <summary>
        /// Gets or sets the minimum monster level.
        /// </summary>
        [Display(Name = "Minimum monster level")]
        public int MinimumMonsterLevel { get; set; } = 1;

        /// <summary>
        /// Gets or sets the maximum monster level.
        /// </summary>
        [Display(Name = "Maximum monster level")]
        public int MaximumMonsterLevel { get; set; } = 130;

        /// <inheritdoc />
        public override string ToString() => $"{this.Name}: {this.ChancePercent}% (monster level {this.MinimumMonsterLevel}-{this.MaximumMonsterLevel})";
    }
}
