// <copyright file="SkillBookDropConfiguration.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.GameLogic.PlugIns;

using MUnique.OpenMU.DataModel.Composition;

/// <summary>
/// The configuration of the <see cref="SkillBookDropPlugIn"/>.
/// </summary>
public class SkillBookDropConfiguration
{
    /// <summary>
    /// Gets or sets a value indicating whether skill books drop in mini games.
    /// </summary>
    [Display(Name = "Apply in mini games", Description = "If enabled, skill books also drop from monsters in mini games.")]
    public bool ApplyInMiniGames { get; set; }

    /// <summary>
    /// Gets or sets the skill books which can drop.
    /// </summary>
    [MemberOfAggregate]
    [ScaffoldColumn(true)]
    [Display(Name = "Skill books", Description = "Every book is rolled independently on each kill of a monster within its level range. Generated by tools/balance/skill_books.py.")]
    public ICollection<SkillBookDropEntry> Books { get; set; } = CreateDefaultBooks();

    private static ICollection<SkillBookDropEntry> CreateDefaultBooks() => new List<SkillBookDropEntry>
    {
        // generated:start
        new() { Name = "Orb of Summoning", ItemGroup = 12, ItemNumber = 11, ChancePercent = 1.0f, MinimumMonsterLevel = 1, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Fire Ball", ItemGroup = 15, ItemNumber = 3, ChancePercent = 0.918f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Healing", ItemGroup = 12, ItemNumber = 8, ChancePercent = 0.808f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Power Wave", ItemGroup = 15, ItemNumber = 10, ChancePercent = 0.774f, MinimumMonsterLevel = 5, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Greater Defense", ItemGroup = 12, ItemNumber = 9, ChancePercent = 0.653f, MinimumMonsterLevel = 10, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Lighting", ItemGroup = 15, ItemNumber = 2, ChancePercent = 0.653f, MinimumMonsterLevel = 10, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Teleport", ItemGroup = 15, ItemNumber = 5, ChancePercent = 0.55f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Greater Damage", ItemGroup = 12, ItemNumber = 10, ChancePercent = 0.527f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Impale", ItemGroup = 12, ItemNumber = 13, ChancePercent = 0.484f, MinimumMonsterLevel = 15, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Meteorite", ItemGroup = 15, ItemNumber = 1, ChancePercent = 0.464f, MinimumMonsterLevel = 20, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Ice", ItemGroup = 15, ItemNumber = 6, ChancePercent = 0.391f, MinimumMonsterLevel = 20, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Poison", ItemGroup = 15, ItemNumber = 0, ChancePercent = 0.316f, MinimumMonsterLevel = 25, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Flame", ItemGroup = 15, ItemNumber = 4, ChancePercent = 0.256f, MinimumMonsterLevel = 30, MaximumMonsterLevel = 130 },
        new() { Name = "Drain Life Parchment", ItemGroup = 15, ItemNumber = 20, ChancePercent = 0.256f, MinimumMonsterLevel = 30, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Twister", ItemGroup = 15, ItemNumber = 7, ChancePercent = 0.206f, MinimumMonsterLevel = 35, MaximumMonsterLevel = 130 },
        new() { Name = "Sleep Parchment", ItemGroup = 15, ItemNumber = 24, ChancePercent = 0.206f, MinimumMonsterLevel = 35, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Twisting Slash", ItemGroup = 12, ItemNumber = 7, ChancePercent = 0.153f, MinimumMonsterLevel = 40, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Evil Spirit", ItemGroup = 15, ItemNumber = 8, ChancePercent = 0.135f, MinimumMonsterLevel = 45, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Greater Fortitude", ItemGroup = 12, ItemNumber = 14, ChancePercent = 0.088f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Fire Slash", ItemGroup = 12, ItemNumber = 16, ChancePercent = 0.088f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Hellfire", ItemGroup = 15, ItemNumber = 9, ChancePercent = 0.088f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Penetration", ItemGroup = 12, ItemNumber = 17, ChancePercent = 0.074f, MinimumMonsterLevel = 55, MaximumMonsterLevel = 130 },
        new() { Name = "Increase Block Parchment", ItemGroup = 15, ItemNumber = 36, ChancePercent = 0.057f, MinimumMonsterLevel = 60, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Death Stab", ItemGroup = 12, ItemNumber = 19, ChancePercent = 0.053f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of FireBurst", ItemGroup = 12, ItemNumber = 21, ChancePercent = 0.048f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Aqua Beam", ItemGroup = 15, ItemNumber = 11, ChancePercent = 0.048f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 130 },
        new() { Name = "Chain Lightning Parchment", ItemGroup = 15, ItemNumber = 19, ChancePercent = 0.046f, MinimumMonsterLevel = 65, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Soul Barrier", ItemGroup = 15, ItemNumber = 15, ChancePercent = 0.043f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Rageful Blow", ItemGroup = 12, ItemNumber = 12, ChancePercent = 0.041f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Cometfall", ItemGroup = 15, ItemNumber = 12, ChancePercent = 0.038f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Damage Reflection Parchment", ItemGroup = 15, ItemNumber = 22, ChancePercent = 0.038f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Chain Drive Parchment", ItemGroup = 15, ItemNumber = 30, ChancePercent = 0.038f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Orb of Ice Arrow", ItemGroup = 12, ItemNumber = 18, ChancePercent = 0.036f, MinimumMonsterLevel = 70, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Critical Damage", ItemGroup = 12, ItemNumber = 23, ChancePercent = 0.034f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Teleport Ally", ItemGroup = 15, ItemNumber = 14, ChancePercent = 0.033f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Berserker Parchment", ItemGroup = 15, ItemNumber = 23, ChancePercent = 0.033f, MinimumMonsterLevel = 75, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Inferno", ItemGroup = 15, ItemNumber = 13, ChancePercent = 0.027f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Dragon Roar Parchment", ItemGroup = 15, ItemNumber = 32, ChancePercent = 0.024f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Increase Health Parchment", ItemGroup = 15, ItemNumber = 35, ChancePercent = 0.024f, MinimumMonsterLevel = 80, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Electric Spark", ItemGroup = 12, ItemNumber = 24, ChancePercent = 0.022f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Ice Storm", ItemGroup = 15, ItemNumber = 17, ChancePercent = 0.022f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Lightning Shock Parchment", ItemGroup = 15, ItemNumber = 21, ChancePercent = 0.022f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Weakness Parchment", ItemGroup = 15, ItemNumber = 26, ChancePercent = 0.022f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Decay", ItemGroup = 15, ItemNumber = 16, ChancePercent = 0.019f, MinimumMonsterLevel = 85, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Summon", ItemGroup = 12, ItemNumber = 22, ChancePercent = 0.017f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Destruction", ItemGroup = 12, ItemNumber = 44, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Multi-Shot", ItemGroup = 12, ItemNumber = 45, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Recovery", ItemGroup = 12, ItemNumber = 46, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Crystal of Flame Strike", ItemGroup = 12, ItemNumber = 47, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Chaotic Diseier", ItemGroup = 12, ItemNumber = 48, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Nova", ItemGroup = 15, ItemNumber = 18, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Wizardry Enhance", ItemGroup = 15, ItemNumber = 28, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Gigantic Storm", ItemGroup = 15, ItemNumber = 29, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Dark Side Parchment", ItemGroup = 15, ItemNumber = 31, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Dragon Slasher Parchment", ItemGroup = 15, ItemNumber = 33, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Ignore Defense Parchment", ItemGroup = 15, ItemNumber = 34, ChancePercent = 0.016f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Scroll of Fire Scream", ItemGroup = 12, ItemNumber = 35, ChancePercent = 0.015f, MinimumMonsterLevel = 90, MaximumMonsterLevel = 130 },
        new() { Name = "Innovation Parchment", ItemGroup = 15, ItemNumber = 27, ChancePercent = 0.01f, MinimumMonsterLevel = 100, MaximumMonsterLevel = 130 },
        // generated:end
    };

    /// <summary>
    /// A skill book which can drop.
    /// </summary>
    public class SkillBookDropEntry
    {
        /// <summary>
        /// Gets or sets the name, only for the overview.
        /// </summary>
        [Display(Name = "Name", Description = "Only for the overview; the item is identified by group and number.")]
        public string Name { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the item group.
        /// </summary>
        [Display(Name = "Item group")]
        public short ItemGroup { get; set; }

        /// <summary>
        /// Gets or sets the item number.
        /// </summary>
        [Display(Name = "Item number")]
        public short ItemNumber { get; set; }

        /// <summary>
        /// Gets or sets the chance per kill in percent.
        /// </summary>
        [Display(Name = "Chance per kill (%)")]
        public float ChancePercent { get; set; }

        /// <summary>
        /// Gets or sets the minimum monster level.
        /// </summary>
        [Display(Name = "Minimum monster level")]
        public int MinimumMonsterLevel { get; set; } = 1;

        /// <summary>
        /// Gets or sets the maximum monster level.
        /// </summary>
        [Display(Name = "Maximum monster level")]
        public int MaximumMonsterLevel { get; set; } = 130;

        /// <inheritdoc />
        public override string ToString() => $"{this.Name}: {this.ChancePercent}% (monster level {this.MinimumMonsterLevel}-{this.MaximumMonsterLevel})";
    }
}
