// <copyright file="EnchantPriceRanks.cs" company="MUnique">
// Licensed under the MIT License. See LICENSE file in the project root for full license information.
// </copyright>

namespace MUnique.OpenMU.GameLogic.Items;

using MUnique.OpenMU.DataModel.Configuration.Items;

/// <summary>
/// The price of enchanting by rank (09.10.2026, wiki §7). Jewel of Bless / Soul: price ranks 3..8 take 1, 2, 3, 4, 5, 6
/// jewels of the stack per level; ranks 1 and 2: 1 Bless gives +3 / +2 levels, 1 Soul one level. Chaos Machine
/// +10..+15: the Bless and Soul of the mix x1 (ranks 1-3), x2 (4-5), x3 (6-8). The first sets of a rank (Dragon,
/// Guardian, Dark Phoenix, Valiant, Glorious) have the price of the rank before. Items without a rank: 1 jewel per level,
/// x1. The client has the same (GameLogic/Items/EnchantPrice.h); the table is generated by tools/balance/enchant_price.py.
/// </summary>
public static class EnchantPriceRanks
{
    /// <summary>
    /// Gets the rank of the price of the item (0 without a rank).
    /// </summary>
    /// <param name="definition">The item definition.</param>
    /// <returns>The rank of the price, 0..8.</returns>
    public static int GetPriceRank(ItemDefinition? definition)
    {
        return definition is not null && PriceRanks.TryGetValue((definition.Group, definition.Number), out var rank) ? rank : 0;
    }

    /// <summary>
    /// Gets the jewels which one use of a Jewel of Bless or Soul takes from the stack, and the levels it gives.
    /// </summary>
    /// <param name="definition">The definition of the enchanted item.</param>
    /// <param name="soul"><c>true</c> for the Jewel of Soul.</param>
    /// <returns>The jewels and the levels.</returns>
    public static (int Jewels, int Levels) GetStep(ItemDefinition? definition, bool soul)
    {
        var rank = GetPriceRank(definition);
        if (rank <= 2)
        {
            return (1, soul || rank == 0 ? 1 : 4 - rank);
        }

        return (rank - 2, 1);
    }

    /// <summary>
    /// Gets the multiplier of the Bless and Soul of the Chaos Machine mixes +10..+15.
    /// </summary>
    /// <param name="definition">The definition of the item of the mix.</param>
    /// <returns>1, 2 or 3.</returns>
    public static int GetChaosMachineMultiplier(ItemDefinition? definition)
    {
        var rank = GetPriceRank(definition);
        return rank >= 6 ? 3 : rank >= 4 ? 2 : 1;
    }

    // generated:start
    private static readonly IReadOnlyDictionary<(byte Group, short Number), byte> PriceRanks = new Dictionary<(byte Group, short Number), byte>
    {
        [(0, 0)] = 1, // Kris
        [(0, 1)] = 1, // Short Sword
        [(0, 2)] = 1, // Rapier
        [(0, 3)] = 2, // Katache
        [(0, 4)] = 1, // Sword of Assassin
        [(0, 5)] = 3, // Blade
        [(0, 6)] = 2, // Gladius
        [(0, 7)] = 2, // Falchion
        [(0, 8)] = 3, // Serpent Sword
        [(0, 9)] = 3, // Sword of Salamander
        [(0, 10)] = 3, // Light Saber
        [(0, 11)] = 3, // Legendary Sword
        [(0, 12)] = 4, // Heliacal Sword
        [(0, 13)] = 4, // Double Blade
        [(0, 14)] = 4, // Lighting Sword
        [(0, 15)] = 4, // Giant Sword
        [(0, 16)] = 5, // Sword of Destruction
        [(0, 17)] = 7, // Dark Breaker
        [(0, 18)] = 7, // Thunder Blade
        [(0, 20)] = 8, // Knight Blade
        [(0, 21)] = 8, // Dark Reign Blade
        [(0, 22)] = 8, // Bone Blade
        [(0, 23)] = 8, // Explosion Blade
        [(0, 24)] = 7, // Daybreak
        [(0, 25)] = 7, // Sword Dancer
        [(0, 31)] = 7, // Rune Blade
        [(0, 32)] = 5, // Sacred Glove
        [(0, 33)] = 6, // Storm Hard Glove
        [(0, 34)] = 7, // Piercing Blade Glove
        [(0, 35)] = 8, // Phoenix Soul Star
        [(1, 0)] = 1, // Small Axe
        [(1, 1)] = 1, // Hand Axe
        [(1, 2)] = 1, // Double Axe
        [(1, 3)] = 2, // Tomahawk
        [(1, 4)] = 2, // Elven Axe
        [(1, 5)] = 3, // Battle Axe
        [(1, 6)] = 3, // Nikkea Axe
        [(1, 7)] = 3, // Larkan Axe
        [(1, 8)] = 4, // Crescent Axe
        [(2, 0)] = 1, // Mace
        [(2, 1)] = 1, // Morning Star
        [(2, 2)] = 2, // Flail
        [(2, 3)] = 3, // Great Hammer
        [(2, 4)] = 5, // Crystal Morning Star
        [(2, 5)] = 5, // Crystal Sword
        [(2, 6)] = 3, // Chaos Dragon Axe
        [(2, 7)] = 6, // Elemental Mace
        [(2, 8)] = 4, // Battle Scepter
        [(2, 9)] = 5, // Master Scepter
        [(2, 10)] = 5, // Great Scepter
        [(2, 11)] = 6, // Lord Scepter
        [(2, 12)] = 8, // Great Lord Scepter
        [(2, 14)] = 8, // Soleil Scepter
        [(2, 15)] = 7, // Shining Scepter
        [(3, 0)] = 3, // Light Spear
        [(3, 1)] = 2, // Spear
        [(3, 2)] = 1, // Dragon Lance
        [(3, 3)] = 2, // Giant Trident
        [(3, 4)] = 3, // Serpent Spear
        [(3, 5)] = 1, // Double Poleaxe
        [(3, 6)] = 2, // Halberd
        [(3, 7)] = 3, // Berdysh
        [(3, 8)] = 4, // Great Scythe
        [(3, 9)] = 4, // Bill of Balrog
        [(3, 10)] = 6, // Dragon Spear
        [(4, 0)] = 1, // Short Bow
        [(4, 1)] = 1, // Bow
        [(4, 2)] = 2, // Elven Bow
        [(4, 3)] = 2, // Battle Bow
        [(4, 4)] = 3, // Tiger Bow
        [(4, 5)] = 4, // Silver Bow
        [(4, 6)] = 3, // Chaos Nature Bow
        [(4, 8)] = 1, // Crossbow
        [(4, 9)] = 1, // Golden Crossbow
        [(4, 10)] = 2, // Arquebus
        [(4, 11)] = 3, // Light Crossbow
        [(4, 12)] = 4, // Serpent Crossbow
        [(4, 13)] = 5, // Bluewing Crossbow
        [(4, 14)] = 5, // Aquagold Crossbow
        [(4, 16)] = 6, // Saint Crossbow
        [(4, 17)] = 6, // Celestial Bow
        [(4, 19)] = 7, // Great Reign Crossbow
        [(4, 20)] = 8, // Arrow Viper Bow
        [(4, 21)] = 8, // Sylph Wind Bow
        [(4, 22)] = 7, // Albatross Bow
        [(5, 0)] = 1, // Skull Staff
        [(5, 1)] = 2, // Angelic Staff
        [(5, 2)] = 3, // Serpent Staff
        [(5, 3)] = 4, // Thunder Staff
        [(5, 4)] = 4, // Gorgon Staff
        [(5, 5)] = 5, // Legendary Staff
        [(5, 6)] = 5, // Staff of Resurrection
        [(5, 7)] = 3, // Chaos Lightning Staff
        [(5, 8)] = 6, // Staff of Destruction
        [(5, 9)] = 7, // Dragon Soul Staff
        [(5, 11)] = 8, // Staff of Kundun
        [(5, 12)] = 8, // Grand Viper Staff
        [(5, 13)] = 7, // Platina Staff
        [(5, 14)] = 1, // Mistery Stick
        [(5, 15)] = 2, // Violent Wind Stick
        [(5, 16)] = 4, // Red Wing Stick
        [(5, 17)] = 5, // Ancient Stick
        [(5, 18)] = 6, // Demonic Stick
        [(5, 19)] = 7, // Storm Blitz Stick
        [(5, 20)] = 8, // Eternal Wing Stick
        [(5, 21)] = 3, // Book of Sahamutt
        [(5, 22)] = 4, // Book of Neil
        [(5, 23)] = 5, // Book of Lagle
        [(7, 1)] = 4, // Dragon Helm
        [(7, 2)] = 1, // Pad Helm
        [(7, 3)] = 4, // Legendary Helm
        [(7, 4)] = 2, // Bone Helm
        [(7, 5)] = 1, // Leather Helm
        [(7, 6)] = 2, // Scale Helm
        [(7, 7)] = 3, // Sphinx Mask
        [(7, 8)] = 3, // Brass Helm
        [(7, 9)] = 4, // Plate Helm
        [(7, 10)] = 1, // Vine Helm
        [(7, 11)] = 2, // Silk Helm
        [(7, 12)] = 3, // Wind Helm
        [(7, 13)] = 4, // Spirit Helm
        [(7, 14)] = 4, // Guardian Helm
        [(7, 16)] = 6, // Black Dragon Helm
        [(7, 17)] = 6, // Dark Phoenix Helm
        [(7, 18)] = 6, // Grand Soul Helm
        [(7, 19)] = 6, // Divine Helm
        [(7, 21)] = 7, // Great Dragon Helm
        [(7, 22)] = 7, // Dark Soul Helm
        [(7, 24)] = 7, // Red Spirit Helm
        [(7, 25)] = 4, // Light Plate Mask
        [(7, 26)] = 5, // Adamantine Mask
        [(7, 27)] = 6, // Dark Steel Mask
        [(7, 28)] = 7, // Dark Master Mask
        [(7, 29)] = 8, // Dragon Knight Helm
        [(7, 30)] = 8, // Venom Mist Helm
        [(7, 31)] = 8, // Sylphid Ray Helm
        [(7, 33)] = 8, // Sunlight Mask
        [(7, 34)] = 5, // Ashcrow Helm
        [(7, 35)] = 5, // Eclipse Helm
        [(7, 36)] = 5, // Iris Helm
        [(7, 38)] = 6, // Glorious Mask
        [(7, 39)] = 1, // Mistery Helm
        [(7, 40)] = 4, // Red Wing Helm
        [(7, 41)] = 5, // Ancient Helm
        [(7, 42)] = 6, // Black Rose Helm
        [(7, 43)] = 8, // Aura Helm
        [(7, 44)] = 7, // Lilium Helm
        [(7, 59)] = 5, // Sacred Helm
        [(7, 60)] = 6, // Storm Hard Helm
        [(7, 61)] = 7, // Piercing Helm
        [(7, 73)] = 8, // Phoenix Soul Helmet
        [(8, 1)] = 4, // Dragon Armor
        [(8, 2)] = 1, // Pad Armor
        [(8, 3)] = 4, // Legendary Armor
        [(8, 4)] = 2, // Bone Armor
        [(8, 5)] = 1, // Leather Armor
        [(8, 6)] = 2, // Scale Armor
        [(8, 7)] = 3, // Sphinx Armor
        [(8, 8)] = 3, // Brass Armor
        [(8, 9)] = 4, // Plate Armor
        [(8, 10)] = 1, // Vine Armor
        [(8, 11)] = 2, // Silk Armor
        [(8, 12)] = 3, // Wind Armor
        [(8, 13)] = 4, // Spirit Armor
        [(8, 14)] = 4, // Guardian Armor
        [(8, 15)] = 6, // Storm Crow Armor
        [(8, 16)] = 6, // Black Dragon Armor
        [(8, 17)] = 6, // Dark Phoenix Armor
        [(8, 18)] = 6, // Grand Soul Armor
        [(8, 19)] = 6, // Divine Armor
        [(8, 20)] = 7, // Thunder Hawk Armor
        [(8, 21)] = 7, // Great Dragon Armor
        [(8, 22)] = 7, // Dark Soul Armor
        [(8, 23)] = 7, // Hurricane Armor
        [(8, 24)] = 7, // Red Sprit Armor
        [(8, 25)] = 4, // Light Plate Armor
        [(8, 26)] = 5, // Adamantine Armor
        [(8, 27)] = 6, // Dark Steel Armor
        [(8, 28)] = 7, // Dark Master Armor
        [(8, 29)] = 8, // Dragon Knight Armor
        [(8, 30)] = 8, // Venom Mist Armor
        [(8, 31)] = 8, // Sylphid Ray Armor
        [(8, 32)] = 8, // Volcano Armor
        [(8, 33)] = 8, // Sunlight Armor
        [(8, 34)] = 5, // Ashcrow Armor
        [(8, 35)] = 5, // Eclipse Armor
        [(8, 36)] = 5, // Iris Armor
        [(8, 37)] = 6, // Valiant Armor
        [(8, 38)] = 6, // Glorious Armor
        [(8, 39)] = 1, // Mistery Armor
        [(8, 40)] = 4, // Red Wing Armor
        [(8, 41)] = 5, // Ancient Armor
        [(8, 42)] = 6, // Black Rose Armor
        [(8, 43)] = 8, // Aura Armor
        [(8, 44)] = 7, // Lilium Armor
        [(8, 59)] = 5, // Sacred Armor
        [(8, 60)] = 6, // Storm Hard Armor
        [(8, 61)] = 7, // Piercing Armor
        [(8, 73)] = 8, // Phoenix Soul Armor
        [(9, 1)] = 4, // Dragon Pants
        [(9, 2)] = 1, // Pad Pants
        [(9, 3)] = 4, // Legendary Pants
        [(9, 4)] = 2, // Bone Pants
        [(9, 5)] = 1, // Leather Pants
        [(9, 6)] = 2, // Scale Pants
        [(9, 7)] = 3, // Sphinx Pants
        [(9, 8)] = 3, // Brass Pants
        [(9, 9)] = 4, // Plate Pants
        [(9, 10)] = 1, // Vine Pants
        [(9, 11)] = 2, // Silk Pants
        [(9, 12)] = 3, // Wind Pants
        [(9, 13)] = 4, // Spirit Pants
        [(9, 14)] = 4, // Guardian Pants
        [(9, 15)] = 6, // Storm Crow Pants
        [(9, 16)] = 6, // Black Dragon Pants
        [(9, 17)] = 6, // Dark Phoenix Pants
        [(9, 18)] = 6, // Grand Soul Pants
        [(9, 19)] = 6, // Divine Pants
        [(9, 20)] = 7, // Thunder Hawk Pants
        [(9, 21)] = 7, // Great Dragon Pants
        [(9, 22)] = 7, // Dark Soul Pants
        [(9, 23)] = 7, // Hurricane Pants
        [(9, 24)] = 7, // Red Spirit Pants
        [(9, 25)] = 4, // Light Plate Pants
        [(9, 26)] = 5, // Adamantine Pants
        [(9, 27)] = 6, // Dark Steel Pants
        [(9, 28)] = 7, // Dark Master Pants
        [(9, 29)] = 8, // Dragon Knight Pants
        [(9, 30)] = 8, // Venom Mist Pants
        [(9, 31)] = 8, // Sylphid Ray Pants
        [(9, 32)] = 8, // Volcano Pants
        [(9, 33)] = 8, // Sunlight Pants
        [(9, 34)] = 5, // Ashcrow Pants
        [(9, 35)] = 5, // Eclipse Pants
        [(9, 36)] = 5, // Iris Pants
        [(9, 37)] = 6, // Valiant Pants
        [(9, 38)] = 6, // Glorious Pants
        [(9, 39)] = 1, // Mistery Pants
        [(9, 40)] = 4, // Red Wing Pants
        [(9, 41)] = 5, // Ancient Pants
        [(9, 42)] = 6, // Black Rose Pants
        [(9, 43)] = 8, // Aura Pants
        [(9, 44)] = 7, // Lilium Pants
        [(9, 59)] = 5, // Sacred Pants
        [(9, 60)] = 6, // Storm Hard Pants
        [(9, 61)] = 7, // Piercing Pants
        [(9, 73)] = 8, // Phoenix Soul Pants
        [(10, 1)] = 4, // Dragon Gloves
        [(10, 2)] = 1, // Pad Gloves
        [(10, 3)] = 4, // Legendary Gloves
        [(10, 4)] = 2, // Bone Gloves
        [(10, 5)] = 1, // Leather Gloves
        [(10, 6)] = 2, // Scale Gloves
        [(10, 7)] = 3, // Sphinx Gloves
        [(10, 8)] = 3, // Brass Gloves
        [(10, 9)] = 4, // Plate Gloves
        [(10, 10)] = 1, // Vine Gloves
        [(10, 11)] = 2, // Silk Gloves
        [(10, 12)] = 3, // Wind Gloves
        [(10, 13)] = 4, // Spirit Gloves
        [(10, 14)] = 4, // Guardian Gloves
        [(10, 15)] = 6, // Storm Crow Gloves
        [(10, 16)] = 6, // Black Dragon Gloves
        [(10, 17)] = 6, // Dark Phoenix Gloves
        [(10, 18)] = 6, // Grand Soul Gloves
        [(10, 19)] = 6, // Divine Gloves
        [(10, 20)] = 7, // Thunder Hawk Gloves
        [(10, 21)] = 7, // Great Dragon Gloves
        [(10, 22)] = 7, // Dark Soul Gloves
        [(10, 23)] = 7, // Hurricane Gloves
        [(10, 24)] = 7, // Red Spirit Gloves
        [(10, 25)] = 4, // Light Plate Gloves
        [(10, 26)] = 5, // Adamantine Gloves
        [(10, 27)] = 6, // Dark Steel Gloves
        [(10, 28)] = 7, // Dark Master Gloves
        [(10, 29)] = 8, // Dragon Knight Gloves
        [(10, 30)] = 8, // Venom Mist Gloves
        [(10, 31)] = 8, // Sylphid Ray Gloves
        [(10, 32)] = 8, // Volcano Gloves
        [(10, 33)] = 8, // Sunlight Gloves
        [(10, 34)] = 5, // Ashcrow Gloves
        [(10, 35)] = 5, // Eclipse Gloves
        [(10, 36)] = 5, // Iris Gloves
        [(10, 37)] = 6, // Valiant Gloves
        [(10, 38)] = 6, // Glorious Gloves
        [(10, 39)] = 1, // Mistery Gloves
        [(10, 40)] = 4, // Red Wing Gloves
        [(10, 41)] = 5, // Ancient Gloves
        [(10, 42)] = 6, // Black Rose Gloves
        [(10, 43)] = 8, // Aura Gloves
        [(10, 44)] = 7, // Lilium Gloves
        [(11, 1)] = 4, // Dragon Boots
        [(11, 2)] = 1, // Pad Boots
        [(11, 3)] = 4, // Legendary Boots
        [(11, 4)] = 2, // Bone Boots
        [(11, 5)] = 1, // Leather Boots
        [(11, 6)] = 2, // Scale Boots
        [(11, 7)] = 3, // Sphinx Boots
        [(11, 8)] = 3, // Brass Boots
        [(11, 9)] = 4, // Plate Boots
        [(11, 10)] = 1, // Vine Boots
        [(11, 11)] = 2, // Silk Boots
        [(11, 12)] = 3, // Wind Boots
        [(11, 13)] = 4, // Spirit Boots
        [(11, 14)] = 4, // Guardian Boots
        [(11, 15)] = 6, // Storm Crow Boots
        [(11, 16)] = 6, // Black Dragon Boots
        [(11, 17)] = 6, // Dark Phoenix Boots
        [(11, 18)] = 6, // Grand Soul Boots
        [(11, 19)] = 6, // Divine Boots
        [(11, 20)] = 7, // Thunder Hawk Boots
        [(11, 21)] = 7, // Great Dragon Boots
        [(11, 22)] = 7, // Dark Soul Boots
        [(11, 23)] = 7, // Hurricane Boots
        [(11, 24)] = 7, // Red Spirit Boots
        [(11, 25)] = 4, // Light Plate Boots
        [(11, 26)] = 5, // Adamantine Boots
        [(11, 27)] = 6, // Dark Steel Boots
        [(11, 28)] = 7, // Dark Master Boots
        [(11, 29)] = 8, // Dragon Knight Boots
        [(11, 30)] = 8, // Venom Mist Boots
        [(11, 31)] = 8, // Sylphid Ray Boots
        [(11, 32)] = 8, // Volcano Boots
        [(11, 33)] = 8, // Sunlight Boots
        [(11, 34)] = 5, // Ashcrow Boots
        [(11, 35)] = 5, // Eclipse Boots
        [(11, 36)] = 5, // Iris Boots
        [(11, 37)] = 6, // Valiant Boots
        [(11, 38)] = 6, // Glorious Boots
        [(11, 39)] = 1, // Mistery Boots
        [(11, 40)] = 4, // Red Wing Boots
        [(11, 41)] = 5, // Ancient Boots
        [(11, 42)] = 6, // Black Rose Boots
        [(11, 43)] = 8, // Aura Boots
        [(11, 44)] = 7, // Lilium Boots
        [(11, 59)] = 5, // Sacred Boots
        [(11, 60)] = 6, // Storm Hard Boots
        [(11, 61)] = 7, // Piercing Boots
        [(11, 73)] = 8, // Phoenix Soul Boots
    };
    // generated:end
}
